readTextFile("Input.txt")

var goblinsCalories = input.split("\n\n")

var goblins = []

goblinsCalories.forEach ((goblin) =>{
  let calories = goblin.split("\n").map (x => parseInt(x,10))

  let eachTot = calories.reduce((acc, curr) => acc + curr, 0)

  goblins.push(eachTot)
})

// console.log(goblins);

var max = Math.max(...goblins);

// console.log(max)

goblins = goblins.filter((x) => { return x !== max});

var max2 = Math.max(...goblins);

goblins = goblins.filter((x) => { return x !== max2});

var max3 = Math.max(...goblins);

var finalResult = max + max2 + max3;

console.log("max", max, "max2", max2, "max3", max3)
console.log("finale", finalResult) 
// ! This is the solution of the second part
// TODO the missing part one.




// PART ONE Generated by ChatGPT
const elfInventories = input.split('\n\n').map(inventory => inventory.split('\n').map(Number));

const elfCalories = elfInventories.map(inventory => inventory.reduce((sum, calories) => sum + calories, 0));

const maxCalories = Math.max(...elfCalories);

console.log(maxCalories);
// The first step is to split the input into an array of Elf inventories, where each inventory is itself an array of calorie values. We do this using the split method with the separator \n\n to split the input by the blank lines.

// Next, we calculate the total Calories for each Elf by using the reduce method to sum up the calorie values in each inventory.

// Finally, we use the Math.max function with the spread operator (...) to find the maximum total Calories among all the Elves.